#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : proj
Version  : 7.2.1
Release  : 23
URL      : https://download.osgeo.org/proj/proj-7.2.1.tar.gz
Source0  : https://download.osgeo.org/proj/proj-7.2.1.tar.gz
Summary  : Coordinate transformation software library
Group    : Development/Tools
License  : MIT
Requires: proj-bin = %{version}-%{release}
Requires: proj-data = %{version}-%{release}
Requires: proj-lib = %{version}-%{release}
Requires: proj-license = %{version}-%{release}
Requires: proj-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : compat-gcc-10-dev
BuildRequires : curl-dev
BuildRequires : pkgconfig(gtest)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libnghttp2)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libtiff-4)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : tiff-dev

%description
# PROJ
PROJ is a generic coordinate transformation software, that transforms
coordinates from one coordinate reference system (CRS) to another.
This includes cartographic projections as well as geodetic transformations.

%package bin
Summary: bin components for the proj package.
Group: Binaries
Requires: proj-data = %{version}-%{release}
Requires: proj-license = %{version}-%{release}

%description bin
bin components for the proj package.


%package data
Summary: data components for the proj package.
Group: Data

%description data
data components for the proj package.


%package dev
Summary: dev components for the proj package.
Group: Development
Requires: proj-lib = %{version}-%{release}
Requires: proj-bin = %{version}-%{release}
Requires: proj-data = %{version}-%{release}
Provides: proj-devel = %{version}-%{release}
Requires: proj = %{version}-%{release}

%description dev
dev components for the proj package.


%package lib
Summary: lib components for the proj package.
Group: Libraries
Requires: proj-data = %{version}-%{release}
Requires: proj-license = %{version}-%{release}

%description lib
lib components for the proj package.


%package license
Summary: license components for the proj package.
Group: Default

%description license
license components for the proj package.


%package man
Summary: man components for the proj package.
Group: Default

%description man
man components for the proj package.


%prep
%setup -q -n proj-7.2.1
cd %{_builddir}/proj-7.2.1

%build
## build_prepend content
export CC=gcc-10
export CXX=g++-10
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1633888122
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static --enable-lto
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1633888122
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/proj
cp %{_builddir}/proj-7.2.1/COPYING %{buildroot}/usr/share/package-licenses/proj/ff8d569976b75bad2e71d78ad1df7a422f1165c9
%make_install
## install_append content
# Set the database journal mode away from WAL so it can be queried read-only
/usr/bin/sqlite3 %{buildroot}/usr/share/proj/proj.db 'PRAGMA journal_mode=DELETE;'
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cct
/usr/bin/cs2cs
/usr/bin/geod
/usr/bin/gie
/usr/bin/invgeod
/usr/bin/invproj
/usr/bin/proj
/usr/bin/projinfo
/usr/bin/projsync

%files data
%defattr(-,root,root,-)
/usr/share/proj/CH
/usr/share/proj/GL27
/usr/share/proj/ITRF2000
/usr/share/proj/ITRF2008
/usr/share/proj/ITRF2014
/usr/share/proj/deformation_model.schema.json
/usr/share/proj/nad.lst
/usr/share/proj/nad27
/usr/share/proj/nad83
/usr/share/proj/other.extra
/usr/share/proj/proj.db
/usr/share/proj/proj.ini
/usr/share/proj/projjson.schema.json
/usr/share/proj/triangulation.schema.json
/usr/share/proj/world

%files dev
%defattr(-,root,root,-)
/usr/include/geodesic.h
/usr/include/proj.h
/usr/include/proj/common.hpp
/usr/include/proj/coordinateoperation.hpp
/usr/include/proj/coordinatesystem.hpp
/usr/include/proj/crs.hpp
/usr/include/proj/datum.hpp
/usr/include/proj/io.hpp
/usr/include/proj/metadata.hpp
/usr/include/proj/nn.hpp
/usr/include/proj/util.hpp
/usr/include/proj_api.h
/usr/include/proj_constants.h
/usr/include/proj_experimental.h
/usr/include/proj_symbol_rename.h
/usr/lib64/libproj.so
/usr/lib64/pkgconfig/proj.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libproj.so.19
/usr/lib64/libproj.so.19.2.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/proj/ff8d569976b75bad2e71d78ad1df7a422f1165c9

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cct.1
/usr/share/man/man1/cs2cs.1
/usr/share/man/man1/geod.1
/usr/share/man/man1/gie.1
/usr/share/man/man1/proj.1
/usr/share/man/man1/projinfo.1
/usr/share/man/man1/projsync.1
